core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from . import views

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # accounts/login/ [name='login']
    # accounts/logout/ [name='logout']
    # accounts/password_change/ [name='password_change']
    # accounts/password_change/done/ [name='password_change_done']
    # accounts/password_reset/ [name='password_reset']
    # accounts/password_reset/done/ [name='password_reset_done']
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']
    re_path(r'^(?P<path>favicon\.ico)$', serve, dict(document_root=settings.STATIC_ROOT)),
    re_path(r'^(?P<path>.+)$', views.handle404),
]

main_app/urls.py
from django.urls import path

from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('files/', views.MainModelListView.as_view(), name='files'),
    path('files/create', views.MainModelCreateView.as_view(), name='create'),
    path('files/<int:pk>/', views.MainModelDetailView.as_view(), name='detail'),
    path('files/<int:pk>/edit', views.MainModelUpdateView.as_view(), name='update'),
    path('files/<int:pk>/delete', views.MainModelDeleteView.as_view(), name='delete'),
    path('files/form_view/', views.form_view, name='form_view'),
    path('files/form_view/<int:pk>', views.form_view, name='form_view'),
    path('files/detail_view/<int:pk>', views.detail_view, name='detail_view'),
    path('set_custom_permission/', views.set_custom_permission, name='set_custom_permission'),
    path('user_model_form/', views.user_model_form, name='user_model_form'),
]

templates/base-form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<form class="form" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock body %}

templates/base-formset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<form class="form" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{ formset|crispy }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{{title}}</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
</head>
<body>
<div style="margin: 3%;">
{% include 'navbar.html' %}
{% block body %}{% endblock body %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</html>

templates/navbar.html
<nav class="navbar navbar-expand
justify-content-center
<!--fixed-top-->
<!--bg-light-->
">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="navbar-brand" href="{% url 'main_app:index' %}">BRAND</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'main_app:index' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'main_app:files' %}">Files</a>
        </li>
        <!--        {% if user.is_staff %}-->
        <!--        <li class="nav-item">-->
        <!--            <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Admin</a>-->
        <!--        </li>-->
        <!--        {% endif %}-->
        <!--        <li class="nav-item dropdown">-->
        <!--            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">-->
        <!--                Dropdown link-->
        <!--            </a>-->
        <!--            <div class="dropdown-menu">-->
        <!--                <a class="dropdown-item" href="">Link 1</a>-->
        <!--                <a class="dropdown-item" href="">Link 2</a>-->
        <!--                <a class="dropdown-item" href="">Link 3</a>-->
        <!--            </div>-->
        <!--        </li>-->
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
                {{ user }}
            </a>
            <div class="dropdown-menu">
                {% if user.is_staff %}
                <span class="dropdown-item">is_staff</span>
                <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">admin</a>

                {% endif %}
                {% if user.is_superuser %}
                <span class="dropdown-item">is_superuser</span>
                {% endif %}
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            </div>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
    </ul>
</nav>
<hr>

templates/pagination.html
{% if page_obj and page_obj.paginator.num_pages > 1 %}
<ul class="pagination justify-content-center">
    {% if page_obj.number == 1 %}
    <li class="page-item disabled">
        <span class="page-link">First</span>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page=1">First</a>
    </li>
    {% endif %}
    {% if page_obj.has_previous %}
    <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <span class="page-link">Previous</span>
    </li>
    {% endif %}
    <li class="page-item active">
        <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <span class="page-link">Next</span>
    </li>
    {% endif %}
    {% if page_obj.number == page_obj.paginator.num_pages %}
    <li class="page-item disabled">
        <span class="page-link">Last</span>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    </li>
    {% endif %}
</ul>
{% endif %}